baseURL: "https://drtbz.com"
languageCode: "en-us"
title: "Overworked servant to the Thing Upstairs"

enableEmoji: true
enableGitInfo: true

sitemap:
  changefreq: monthly
  filename: sitemap.xml
  priority: 0.5

theme: "ananke"

copyright: "Copyright {year}. All rights reserved."
