name: hugo -> pages

on:
  push:
    paths:
      - '**.md'
      - '!README.md'
      - '!CODE_OF_CONDUCT.md'
      - '!.github/**'
    branches:
      - main  # Set a branch to deploy
  pull_request:

jobs:
  deploy:
    environment: hugo
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
